version: '3'
services:
  server:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://dbsuer:dbpassword@db:5432/dbname
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_JWT_SECRET: "reallyreallyreallyreallyverysafe"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: dbsuer
      POSTGRES_PASSWORD: dbpassword
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/
  pgadmin4:
    image: dpage/pgadmin4
    volumes:
      - ./volumes/pdadmin4-data:/var/lib/pgadmin
    ports:
      - "8090:80"
    expose:
      - "8090"
    environment:
      - PGADMIN_DEFAULT_EMAIL=email@localhost.com
      - PGADMIN_DEFAULT_PASSWORD=dbpassword
    depends_on:
      - db
      - server
      - swagger